# Generated by Django 2.2.1 on 2019-06-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('cc_name', models.TextField(max_length=50)),
                ('cc_number', models.CharField(max_length=50, unique=True)),
                ('cc_valid_date', models.CharField(max_length=5, null=True)),
                ('cc_code', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
    ]
