# Generated by Django 2.2.1 on 2019-06-25 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditCard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='cc_charge',
        ),
    ]
