# Generated by Django 2.2.1 on 2019-06-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditCard', '0002_remove_creditcard_cc_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cc_code',
            field=models.CharField(max_length=3, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='cc_number',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
