# Generated by Django 2.2.1 on 2019-06-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditCard', '0003_auto_20190625_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cc_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
