# Generated by Django 2.2.1 on 2019-06-16 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20190616_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='emailId',
        ),
    ]
