# Generated by Django 2.2.1 on 2019-06-16 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20190617_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='emailId',
            new_name='email_address',
        ),
    ]
