# Generated by Django 2.2.1 on 2019-06-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Salads', 'Salads'), ('Desserts', 'Desserts'), ('Fruits', 'Fruits'), ('Beverages', 'Beverages'), ('Favorite', 'Favorite')], max_length=120),
        ),
    ]
